version: '2'

services:
  web:
    restart: always
    build: ./web
    expose:
        - "8000"
    volumes:
      - /usr/src/app/web
    command: ./wait-for-it.sh postgres:5432 -- /usr/local/bin/gunicorn -w 2 -b 127.0.0.1:8000 project:app
    networks:
      - db_nw
      - web_nw
    depends_on:
      - postgres

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    networks:
      - web_nw
    volumes_from:
      - web
    depends_on:
      - web

  postgres:
    restart: always
    build: ./postgresql
    expose:
      - "5432"
    volumes:
      - /var/lib/postgresql
    networks:
      - db_nw

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
