version: '2'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - /usr/src/app/web/project/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 project:app
    depends_on:
      - postgres
    networks:
      - db_nw
      - web_nw

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
      - web
    networks:
      - web_nw


  webinit:
    restart: always
    build: ./webinit
    volumes:
      - /usr/src/app/web/project/static
    command: >
      /bin/bash -c "
        sleep 60;
        python run.py;
      "
    depends_on:
      - postgres
    networks:
      - db_nw

  postgres:
    restart: always
    build: ./postgresql
    volumes:
      - /var/lib/postgresql
    expose:
      - "5432"
    networks:
      - db_nw
      
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
