version: '2'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - /usr/src/app/web/project/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 project:app
	networks:
      - db_nw
      - web_nw
    depends_on:
      - postgres

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
	networks:
      - web_nw
    depends_on:
      - web

  postgres:
    restart: always
    build: ./postgresql
    expose:
      - "5432"
	volumes:
      - /var/lib/postgresql
	networks:
      - db_nw

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
